AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
  TargetRubyVersion: 3.1

Style/FormatString:
  EnforcedStyle: sprintf
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/StringConcatenation:
  Mode: conservative
Style/Documentation:
  Exclude:
    - app/helpers/*_helper.rb
    - db/migrate/*
    - test/**/*
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/PerlBackrefs:
  Exclude:
    - lib/netkeiba/race_base_page.rb
    - lib/netkeiba/race_page.rb
Style/RedundantSelf:
  Exclude:
    - lib/uma2/positives.rb
    - lib/uma2/probability.rb

Naming/MethodParameterName:
  Exclude:
    - lib/uma2/positives.rb
    - lib/uma2/probability.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedColonStyle: table
  Exclude:
    - lib/netkeiba/race_page.rb
    - spec/jobs/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - spec/**/*_spec.rb
Metrics/MethodLength:
  Max: 15
  Exclude:
    - spec/jobs/*_spec.rb
Metrics/AbcSize:
  Max: 18
