AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - db/schema.rb
  TargetRubyVersion: 3.1

Style/FormatString:
  EnforcedStyle: sprintf
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/StringConcatenation:
  Mode: conservative
Style/Documentation:
  Exclude:
    - app/helpers/*_helper.rb
    - db/migrate/*
    - test/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
Metrics/MethodLength:
  Max: 15
