# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DBHOST') { 'localhost' } %>
  username: <%= ENV.fetch('DBUSER') { 'dbuser' } %>
  password: <%= ENV.fetch('DBPASSWORD') { 'password' } %>
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DBNAME_DEV') { 'dbname_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DBNAME_TEST') { 'dbname_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DBNAME_PROD') { 'dbname_prod' } %>
