<% Dotenv::Railtie.load %>
---
app_name: <%= ENV.fetch('APP_NAME'){ 'APP_NAME' } %>
redis:
  url: <%= ENV.fetch('REDIS_URL'){ 'redis://localhost:6379' } %>
  namespace: <%= ENV.fetch('REDIS_NAMESPACE'){ 'general' } %>
uma2:
  learning_rate: <%= ENV.fetch('UMA2_LEARNING_RATE'){ '0.01' }.to_f %>
  iteration: <%= ENV.fetch('UMA2_ITERATION_PER_JOB'){ '100' }.to_i %>
  convergence_margin: <%= ENV.fetch('UMA2_CONVERGENCE_MARGIN'){ '1e-5' }.to_f %>
  check_loss_margin: <%= ENV.fetch('UMA2_CHECK_LOSS_MARGIN'){ '1e-6' }.to_f %>
  check_loss_interval: <%= ENV.fetch('UMA2_CHECK_LOSS_INTERVAL'){ '10' }.to_i %>
  nonnegative_margin: <%= ENV.fetch('UMA2_NONNEGATIVE_MARGIN'){ '1e-5' }.to_f %>
  initial_certainty: <%= ENV.fetch('UMA2_INITIAL_CERTAINTY'){ '1.0' }.to_f %>
  proposer:
    hit_probability_min: <%= ENV.fetch('UMA2_PROPOSER_HIT_PROBABILITY_MIN'){ '0.8' }.to_f %>
  scheduler:
    after_wait_minutes: <%= ENV.fetch('UMA2_SCHEDULER_AFTER_WAIT_MINUTES'){ '30' }.to_i %>
app:
  race:
    bet: <%= ENV.fetch('APP_RACE_PROPOSER_BET'){ '10' }.to_i %>
